### ISSUE TITLE
Sprint 2 Fahrzeug zurückgeben

### ISSUE THREAD

**Issue by KanBen86** [KanBen86/ProjektCarsharing#10]
- [x] Datenbank:
   - [x] Methoden für die Interaktionen auf dem Fahrzeug
   - [x] Entität Buchung anpassen um eine Beschreibung für die Rückgabe zu ermöglichen 
- [x] Servlets:
   - [x] Servlet zurückgeben erstellen ("return/{id}")
        - [x] doGet
        - [x] doPost
   - [x] Servlet für alle Buchungen erstellen ("bookings")
        - [x] doGet
        - [x] doPost
- [x] UI:
   - [x] Header bekommt ein Button Buchungen:
        - [x] verweist auf eine neue Liste (wie Index) mit alles gebuchten Fahrzeugen
        - [x] Button Buchen für FahrzeugStatus gebucht 
        - [x] Button Zurückkgeben einfügen
   - [x] jsp für das Zurückgeben -> neuer Fahrzeugstatuts
       - [x] Auswahl des Status
       - [x] Eingabe einer Nachricht

Zu erledigen bis: 19.03.

**Comment by OrlandoJae** [comment]
Abgeschlossen am 18.03.19
