### ISSUE TITLE
Sprint 1 Fahrzeug ausleihen

### ISSUE THREAD

**Issue by KanBen86** [KanBen86/ProjektCarsharing#8]
- [x] DB:
   - [x] Datenstruktur (POJO)
   - [x] Datenbankaktionen (Beans)
- [x] Servlet:
   - [x] Request Übersicht
   - [x] Request für Detail mit Übergabe ID Fahrzeug
   - [x] Methode Buchen mit DB-Proxyaufruf (Beans)
- [x] UI:
   - [x] Übersichtsseite
   - [x] Detailseite
   - [x] Button Buchen
   - [x] Button Detail
- [x] Sonstiges:
   - [x] Enums für die Stati
   - [x] Testfahrzeuge anlegen

Zu erledigen bis 03.03.19 -> 11.03.19

**Comment by KanBen86** [comment]
Entität für das Fahrzeug erzeugt und die benötigten Felder mit samt den Enums angelegt. Enums können bei Bedarf ergänzt werden

**Comment by KanBen86** [comment]
Fahrzeug Entität und Bean fertig

**Comment by KanBen86** [comment]
Sprint erweitert, da sich die Test noch nicht vollständig gelaufen sind.

**Comment by KanBen86** [comment]
INSERT INTO KA_SHARING.FAHRZEUG VALUES (1 , null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);

**Comment by KanBen86** [comment]
UPDATE KA_SHARING.FAHRZEUG SET ANSCHAFFUNGSPREIS = 12334.55 WHERE ID = 1;

**Comment by ChrisPschibila** [comment]
Der Button "Detail" ist jetzt auf der Übersichtsseite vorhanden und wenn man drauf klickt, wird man auf die Detailseite geroutet

**Comment by KanBen86** [comment]
-- DROP TABLE KA_SHARING.FAHRZEUG;
INSERT INTO KA_SHARING.FAHRZEUG VALUES (1 , 1, null, 12345.67, 'Elegance', 1, 1, 1, 2, 2, null, 5, 2, 0, 4, 'A-Klasse', 2, 4, 123.45, 4, 1, 1);
INSERT INTO KA_SHARING.FAHRZEUG VALUES (2 , 1, null, 21345.67, 'Sport', 1, 1, 1, 2, 2, null, 5, 2, 0, 4, 'B-Klasse', 2, 4, 123.45, 4, 1, 1);
INSERT INTO KA_SHARING.FAHRZEUG VALUES (3 , 1, null, 32145.67, 'Avangarde', 1, 1, 1, 2, 2, null, 5, 2, 0, 4, 'C-Klasse', 2, 4, 123.45, 4, 1, 1);
INSERT INTO KA_SHARING.FAHRZEUG VALUES (4 , 1, null, 45123.67, 'Elegance', 1, 1, 1, 2, 2, null, 5, 2, 0, 4, 'E-Klasse', 2, 4, 123.45, 4, 1, 1);
INSERT INTO KA_SHARING.FAHRZEUG VALUES (5 , 1, null, 54321.67, 'Elegance', 1, 1, 1, 2, 2, null, 5, 2, 0, 4, 'S-Klasse', 2, 4, 123.45, 4, 1, 1);
SELECT * FROM KA_SHARING.FAHRZEUG;

**Comment by ChrisPschibila** [comment]
${nutzer=='Kunde' ? 'readonly' : ''}

Wird später benötigt, wenn man den Nutzertyp unterscheidet (Kunde bzw. Sachbearbeiter)

**Comment by KanBen86** [comment]
Sprint am 17.03. erledigt. Test hat funktioniert
